language: shell
sudo: required
services:
  - docker
env:
  - PGHOST=localhost
  - PGPORT=6666
  - POSTGRES_VERSION=11.0
  - POSTGRES_VERSION=10.5
  - POSTGRES_VERSION=9.6
  - POSTGRES_VERSION=9.5
  - POSTGRES_VERSION=9.4
  - POSTGRES_VERSION=9.3

before_install:
  - docker run -d -p 6666:5432 postgres:${POSTGRES_VERSION}
  - sleep 5 # naively wait for postgres container to start properly
script:
  - psql -h ${PGHOST} -p ${PGPORT} -U postgres -d postgres -c 'SELECT version();'
